CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_email 
ON users (email) WHERE email IS NOT NULL;
