FROM node:24-alpine

WORKDIR /app

# Install deps
COPY package.json package-lock.json* ./
RUN npm ci

# Copy source for dev
COPY . .

USER root
EXPOSE 3000
ENV HOSTNAME="0.0.0.0" \
    PORT=3000

CMD ["npm", "run", "dev"]
